name: Test Cron Job
on:
  schedule:
    - cron: '0 */11 * * *'

jobs:
  test_cron_job:
    name: Test Cron Job Execution
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cron job executed successfully!"
      

